// source: proto/com/wixpress/dst/greyhound/sidecar/api/v1/greyhoundsidecar.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
goog.object.extend(proto, google_protobuf_wrappers_pb);
var google_protobuf_struct_pb = require('google-protobuf/google/protobuf/struct_pb.js');
goog.object.extend(proto, google_protobuf_struct_pb);
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
goog.exportSymbol('proto.com.wixpress.dst.greyhound.sidecar.api.v1.Consumer', null, global);
goog.exportSymbol('proto.com.wixpress.dst.greyhound.sidecar.api.v1.CreateTopicsRequest', null, global);
goog.exportSymbol('proto.com.wixpress.dst.greyhound.sidecar.api.v1.CreateTopicsResponse', null, global);
goog.exportSymbol('proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceRequest', null, global);
goog.exportSymbol('proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceRequest.TargetCase', null, global);
goog.exportSymbol('proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceResponse', null, global);
goog.exportSymbol('proto.com.wixpress.dst.greyhound.sidecar.api.v1.RegisterRequest', null, global);
goog.exportSymbol('proto.com.wixpress.dst.greyhound.sidecar.api.v1.RegisterResponse', null, global);
goog.exportSymbol('proto.com.wixpress.dst.greyhound.sidecar.api.v1.StartConsumingRequest', null, global);
goog.exportSymbol('proto.com.wixpress.dst.greyhound.sidecar.api.v1.StartConsumingResponse', null, global);
goog.exportSymbol('proto.com.wixpress.dst.greyhound.sidecar.api.v1.TopicToCreate', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.RegisterRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.wixpress.dst.greyhound.sidecar.api.v1.RegisterRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.wixpress.dst.greyhound.sidecar.api.v1.RegisterRequest.displayName = 'proto.com.wixpress.dst.greyhound.sidecar.api.v1.RegisterRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.RegisterResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.wixpress.dst.greyhound.sidecar.api.v1.RegisterResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.wixpress.dst.greyhound.sidecar.api.v1.RegisterResponse.displayName = 'proto.com.wixpress.dst.greyhound.sidecar.api.v1.RegisterResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.StartConsumingRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.wixpress.dst.greyhound.sidecar.api.v1.StartConsumingRequest.repeatedFields_, null);
};
goog.inherits(proto.com.wixpress.dst.greyhound.sidecar.api.v1.StartConsumingRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.wixpress.dst.greyhound.sidecar.api.v1.StartConsumingRequest.displayName = 'proto.com.wixpress.dst.greyhound.sidecar.api.v1.StartConsumingRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.Consumer = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.wixpress.dst.greyhound.sidecar.api.v1.Consumer, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.wixpress.dst.greyhound.sidecar.api.v1.Consumer.displayName = 'proto.com.wixpress.dst.greyhound.sidecar.api.v1.Consumer';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.StartConsumingResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.wixpress.dst.greyhound.sidecar.api.v1.StartConsumingResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.wixpress.dst.greyhound.sidecar.api.v1.StartConsumingResponse.displayName = 'proto.com.wixpress.dst.greyhound.sidecar.api.v1.StartConsumingResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceRequest.oneofGroups_);
};
goog.inherits(proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceRequest.displayName = 'proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceResponse.displayName = 'proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.CreateTopicsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.wixpress.dst.greyhound.sidecar.api.v1.CreateTopicsRequest.repeatedFields_, null);
};
goog.inherits(proto.com.wixpress.dst.greyhound.sidecar.api.v1.CreateTopicsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.wixpress.dst.greyhound.sidecar.api.v1.CreateTopicsRequest.displayName = 'proto.com.wixpress.dst.greyhound.sidecar.api.v1.CreateTopicsRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.TopicToCreate = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.wixpress.dst.greyhound.sidecar.api.v1.TopicToCreate, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.wixpress.dst.greyhound.sidecar.api.v1.TopicToCreate.displayName = 'proto.com.wixpress.dst.greyhound.sidecar.api.v1.TopicToCreate';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.CreateTopicsResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.wixpress.dst.greyhound.sidecar.api.v1.CreateTopicsResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.wixpress.dst.greyhound.sidecar.api.v1.CreateTopicsResponse.displayName = 'proto.com.wixpress.dst.greyhound.sidecar.api.v1.CreateTopicsResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.RegisterRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.com.wixpress.dst.greyhound.sidecar.api.v1.RegisterRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.RegisterRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.RegisterRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    host: jspb.Message.getFieldWithDefault(msg, 1, ""),
    port: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.RegisterRequest}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.RegisterRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.wixpress.dst.greyhound.sidecar.api.v1.RegisterRequest;
  return proto.com.wixpress.dst.greyhound.sidecar.api.v1.RegisterRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.RegisterRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.RegisterRequest}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.RegisterRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setHost(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setPort(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.RegisterRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.wixpress.dst.greyhound.sidecar.api.v1.RegisterRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.RegisterRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.RegisterRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHost();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPort();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string host = 1;
 * @return {string}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.RegisterRequest.prototype.getHost = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.RegisterRequest} returns this
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.RegisterRequest.prototype.setHost = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string port = 2;
 * @return {string}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.RegisterRequest.prototype.getPort = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.RegisterRequest} returns this
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.RegisterRequest.prototype.setPort = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.RegisterResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.com.wixpress.dst.greyhound.sidecar.api.v1.RegisterResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.RegisterResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.RegisterResponse.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.RegisterResponse}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.RegisterResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.wixpress.dst.greyhound.sidecar.api.v1.RegisterResponse;
  return proto.com.wixpress.dst.greyhound.sidecar.api.v1.RegisterResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.RegisterResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.RegisterResponse}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.RegisterResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.RegisterResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.wixpress.dst.greyhound.sidecar.api.v1.RegisterResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.RegisterResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.RegisterResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.StartConsumingRequest.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.StartConsumingRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.com.wixpress.dst.greyhound.sidecar.api.v1.StartConsumingRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.StartConsumingRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.StartConsumingRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    consumersList: jspb.Message.toObjectList(msg.getConsumersList(),
    proto.com.wixpress.dst.greyhound.sidecar.api.v1.Consumer.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.StartConsumingRequest}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.StartConsumingRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.wixpress.dst.greyhound.sidecar.api.v1.StartConsumingRequest;
  return proto.com.wixpress.dst.greyhound.sidecar.api.v1.StartConsumingRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.StartConsumingRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.StartConsumingRequest}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.StartConsumingRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = new proto.com.wixpress.dst.greyhound.sidecar.api.v1.Consumer;
      reader.readMessage(value,proto.com.wixpress.dst.greyhound.sidecar.api.v1.Consumer.deserializeBinaryFromReader);
      msg.addConsumers(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.StartConsumingRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.wixpress.dst.greyhound.sidecar.api.v1.StartConsumingRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.StartConsumingRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.StartConsumingRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getConsumersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.com.wixpress.dst.greyhound.sidecar.api.v1.Consumer.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Consumer consumers = 2;
 * @return {!Array<!proto.com.wixpress.dst.greyhound.sidecar.api.v1.Consumer>}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.StartConsumingRequest.prototype.getConsumersList = function() {
  return /** @type{!Array<!proto.com.wixpress.dst.greyhound.sidecar.api.v1.Consumer>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.com.wixpress.dst.greyhound.sidecar.api.v1.Consumer, 2));
};


/**
 * @param {!Array<!proto.com.wixpress.dst.greyhound.sidecar.api.v1.Consumer>} value
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.StartConsumingRequest} returns this
*/
proto.com.wixpress.dst.greyhound.sidecar.api.v1.StartConsumingRequest.prototype.setConsumersList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.Consumer=} opt_value
 * @param {number=} opt_index
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.Consumer}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.StartConsumingRequest.prototype.addConsumers = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.com.wixpress.dst.greyhound.sidecar.api.v1.Consumer, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.StartConsumingRequest} returns this
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.StartConsumingRequest.prototype.clearConsumersList = function() {
  return this.setConsumersList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.Consumer.prototype.toObject = function(opt_includeInstance) {
  return proto.com.wixpress.dst.greyhound.sidecar.api.v1.Consumer.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.Consumer} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.Consumer.toObject = function(includeInstance, msg) {
  var f, obj = {
    group: jspb.Message.getFieldWithDefault(msg, 2, ""),
    topic: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.Consumer}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.Consumer.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.wixpress.dst.greyhound.sidecar.api.v1.Consumer;
  return proto.com.wixpress.dst.greyhound.sidecar.api.v1.Consumer.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.Consumer} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.Consumer}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.Consumer.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setGroup(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setTopic(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.Consumer.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.wixpress.dst.greyhound.sidecar.api.v1.Consumer.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.Consumer} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.Consumer.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getGroup();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTopic();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string group = 2;
 * @return {string}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.Consumer.prototype.getGroup = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.Consumer} returns this
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.Consumer.prototype.setGroup = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string topic = 3;
 * @return {string}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.Consumer.prototype.getTopic = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.Consumer} returns this
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.Consumer.prototype.setTopic = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.StartConsumingResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.com.wixpress.dst.greyhound.sidecar.api.v1.StartConsumingResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.StartConsumingResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.StartConsumingResponse.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.StartConsumingResponse}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.StartConsumingResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.wixpress.dst.greyhound.sidecar.api.v1.StartConsumingResponse;
  return proto.com.wixpress.dst.greyhound.sidecar.api.v1.StartConsumingResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.StartConsumingResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.StartConsumingResponse}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.StartConsumingResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.StartConsumingResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.wixpress.dst.greyhound.sidecar.api.v1.StartConsumingResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.StartConsumingResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.StartConsumingResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceRequest.oneofGroups_ = [[3]];

/**
 * @enum {number}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceRequest.TargetCase = {
  TARGET_NOT_SET: 0,
  KEY: 3
};

/**
 * @return {proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceRequest.TargetCase}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceRequest.prototype.getTargetCase = function() {
  return /** @type {proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceRequest.TargetCase} */(jspb.Message.computeOneofCase(this, proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceRequest.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    topic: jspb.Message.getFieldWithDefault(msg, 1, ""),
    payload: (f = msg.getPayload()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    key: jspb.Message.getFieldWithDefault(msg, 3, ""),
    customHeadersMap: (f = msg.getCustomHeadersMap()) ? f.toObject(includeInstance, undefined) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceRequest}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceRequest;
  return proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceRequest}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTopic(value);
      break;
    case 2:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setPayload(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setKey(value);
      break;
    case 4:
      var value = msg.getCustomHeadersMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTopic();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPayload();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getCustomHeadersMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(4, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
};


/**
 * optional string topic = 1;
 * @return {string}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceRequest.prototype.getTopic = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceRequest} returns this
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceRequest.prototype.setTopic = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional google.protobuf.StringValue payload = 2;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceRequest.prototype.getPayload = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 2));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceRequest} returns this
*/
proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceRequest.prototype.setPayload = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceRequest} returns this
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceRequest.prototype.clearPayload = function() {
  return this.setPayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceRequest.prototype.hasPayload = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string key = 3;
 * @return {string}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceRequest.prototype.getKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceRequest} returns this
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceRequest.prototype.setKey = function(value) {
  return jspb.Message.setOneofField(this, 3, proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceRequest.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceRequest} returns this
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceRequest.prototype.clearKey = function() {
  return jspb.Message.setOneofField(this, 3, proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceRequest.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceRequest.prototype.hasKey = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * map<string, string> custom_headers = 4;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceRequest.prototype.getCustomHeadersMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 4, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceRequest} returns this
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceRequest.prototype.clearCustomHeadersMap = function() {
  this.getCustomHeadersMap().clear();
  return this;};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceResponse.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceResponse}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceResponse;
  return proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceResponse}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.ProduceResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.CreateTopicsRequest.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.CreateTopicsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.com.wixpress.dst.greyhound.sidecar.api.v1.CreateTopicsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.CreateTopicsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.CreateTopicsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    topicsList: jspb.Message.toObjectList(msg.getTopicsList(),
    proto.com.wixpress.dst.greyhound.sidecar.api.v1.TopicToCreate.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.CreateTopicsRequest}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.CreateTopicsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.wixpress.dst.greyhound.sidecar.api.v1.CreateTopicsRequest;
  return proto.com.wixpress.dst.greyhound.sidecar.api.v1.CreateTopicsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.CreateTopicsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.CreateTopicsRequest}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.CreateTopicsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.com.wixpress.dst.greyhound.sidecar.api.v1.TopicToCreate;
      reader.readMessage(value,proto.com.wixpress.dst.greyhound.sidecar.api.v1.TopicToCreate.deserializeBinaryFromReader);
      msg.addTopics(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.CreateTopicsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.wixpress.dst.greyhound.sidecar.api.v1.CreateTopicsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.CreateTopicsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.CreateTopicsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTopicsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.com.wixpress.dst.greyhound.sidecar.api.v1.TopicToCreate.serializeBinaryToWriter
    );
  }
};


/**
 * repeated TopicToCreate topics = 1;
 * @return {!Array<!proto.com.wixpress.dst.greyhound.sidecar.api.v1.TopicToCreate>}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.CreateTopicsRequest.prototype.getTopicsList = function() {
  return /** @type{!Array<!proto.com.wixpress.dst.greyhound.sidecar.api.v1.TopicToCreate>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.com.wixpress.dst.greyhound.sidecar.api.v1.TopicToCreate, 1));
};


/**
 * @param {!Array<!proto.com.wixpress.dst.greyhound.sidecar.api.v1.TopicToCreate>} value
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.CreateTopicsRequest} returns this
*/
proto.com.wixpress.dst.greyhound.sidecar.api.v1.CreateTopicsRequest.prototype.setTopicsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.TopicToCreate=} opt_value
 * @param {number=} opt_index
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.TopicToCreate}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.CreateTopicsRequest.prototype.addTopics = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.com.wixpress.dst.greyhound.sidecar.api.v1.TopicToCreate, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.CreateTopicsRequest} returns this
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.CreateTopicsRequest.prototype.clearTopicsList = function() {
  return this.setTopicsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.TopicToCreate.prototype.toObject = function(opt_includeInstance) {
  return proto.com.wixpress.dst.greyhound.sidecar.api.v1.TopicToCreate.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.TopicToCreate} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.TopicToCreate.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    partitions: (f = msg.getPartitions()) && google_protobuf_wrappers_pb.Int32Value.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.TopicToCreate}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.TopicToCreate.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.wixpress.dst.greyhound.sidecar.api.v1.TopicToCreate;
  return proto.com.wixpress.dst.greyhound.sidecar.api.v1.TopicToCreate.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.TopicToCreate} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.TopicToCreate}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.TopicToCreate.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = new google_protobuf_wrappers_pb.Int32Value;
      reader.readMessage(value,google_protobuf_wrappers_pb.Int32Value.deserializeBinaryFromReader);
      msg.setPartitions(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.TopicToCreate.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.wixpress.dst.greyhound.sidecar.api.v1.TopicToCreate.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.TopicToCreate} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.TopicToCreate.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPartitions();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_wrappers_pb.Int32Value.serializeBinaryToWriter
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.TopicToCreate.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.TopicToCreate} returns this
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.TopicToCreate.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional google.protobuf.Int32Value partitions = 2;
 * @return {?proto.google.protobuf.Int32Value}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.TopicToCreate.prototype.getPartitions = function() {
  return /** @type{?proto.google.protobuf.Int32Value} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.Int32Value, 2));
};


/**
 * @param {?proto.google.protobuf.Int32Value|undefined} value
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.TopicToCreate} returns this
*/
proto.com.wixpress.dst.greyhound.sidecar.api.v1.TopicToCreate.prototype.setPartitions = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.TopicToCreate} returns this
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.TopicToCreate.prototype.clearPartitions = function() {
  return this.setPartitions(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.TopicToCreate.prototype.hasPartitions = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.CreateTopicsResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.com.wixpress.dst.greyhound.sidecar.api.v1.CreateTopicsResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.CreateTopicsResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.CreateTopicsResponse.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.CreateTopicsResponse}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.CreateTopicsResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.wixpress.dst.greyhound.sidecar.api.v1.CreateTopicsResponse;
  return proto.com.wixpress.dst.greyhound.sidecar.api.v1.CreateTopicsResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.CreateTopicsResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.CreateTopicsResponse}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.CreateTopicsResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.CreateTopicsResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.wixpress.dst.greyhound.sidecar.api.v1.CreateTopicsResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.CreateTopicsResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.CreateTopicsResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};


goog.object.extend(exports, proto.com.wixpress.dst.greyhound.sidecar.api.v1);
