// source: proto/com/wixpress/dst/greyhound/sidecar/api/v1/greyhoundsidecaruser.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
goog.object.extend(proto, google_protobuf_wrappers_pb);
goog.exportSymbol('proto.com.wixpress.dst.greyhound.sidecar.api.v1.HandleMessagesRequest', null, global);
goog.exportSymbol('proto.com.wixpress.dst.greyhound.sidecar.api.v1.HandleMessagesResponse', null, global);
goog.exportSymbol('proto.com.wixpress.dst.greyhound.sidecar.api.v1.Record', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.HandleMessagesRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.wixpress.dst.greyhound.sidecar.api.v1.HandleMessagesRequest.repeatedFields_, null);
};
goog.inherits(proto.com.wixpress.dst.greyhound.sidecar.api.v1.HandleMessagesRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.wixpress.dst.greyhound.sidecar.api.v1.HandleMessagesRequest.displayName = 'proto.com.wixpress.dst.greyhound.sidecar.api.v1.HandleMessagesRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.Record = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.wixpress.dst.greyhound.sidecar.api.v1.Record, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.wixpress.dst.greyhound.sidecar.api.v1.Record.displayName = 'proto.com.wixpress.dst.greyhound.sidecar.api.v1.Record';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.HandleMessagesResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.wixpress.dst.greyhound.sidecar.api.v1.HandleMessagesResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.wixpress.dst.greyhound.sidecar.api.v1.HandleMessagesResponse.displayName = 'proto.com.wixpress.dst.greyhound.sidecar.api.v1.HandleMessagesResponse';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.HandleMessagesRequest.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.HandleMessagesRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.com.wixpress.dst.greyhound.sidecar.api.v1.HandleMessagesRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.HandleMessagesRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.HandleMessagesRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    group: jspb.Message.getFieldWithDefault(msg, 1, ""),
    topic: jspb.Message.getFieldWithDefault(msg, 2, ""),
    recordsList: jspb.Message.toObjectList(msg.getRecordsList(),
    proto.com.wixpress.dst.greyhound.sidecar.api.v1.Record.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.HandleMessagesRequest}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.HandleMessagesRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.wixpress.dst.greyhound.sidecar.api.v1.HandleMessagesRequest;
  return proto.com.wixpress.dst.greyhound.sidecar.api.v1.HandleMessagesRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.HandleMessagesRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.HandleMessagesRequest}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.HandleMessagesRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setGroup(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTopic(value);
      break;
    case 3:
      var value = new proto.com.wixpress.dst.greyhound.sidecar.api.v1.Record;
      reader.readMessage(value,proto.com.wixpress.dst.greyhound.sidecar.api.v1.Record.deserializeBinaryFromReader);
      msg.addRecords(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.HandleMessagesRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.wixpress.dst.greyhound.sidecar.api.v1.HandleMessagesRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.HandleMessagesRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.HandleMessagesRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getGroup();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTopic();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getRecordsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.com.wixpress.dst.greyhound.sidecar.api.v1.Record.serializeBinaryToWriter
    );
  }
};


/**
 * optional string group = 1;
 * @return {string}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.HandleMessagesRequest.prototype.getGroup = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.HandleMessagesRequest} returns this
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.HandleMessagesRequest.prototype.setGroup = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string topic = 2;
 * @return {string}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.HandleMessagesRequest.prototype.getTopic = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.HandleMessagesRequest} returns this
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.HandleMessagesRequest.prototype.setTopic = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated Record records = 3;
 * @return {!Array<!proto.com.wixpress.dst.greyhound.sidecar.api.v1.Record>}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.HandleMessagesRequest.prototype.getRecordsList = function() {
  return /** @type{!Array<!proto.com.wixpress.dst.greyhound.sidecar.api.v1.Record>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.com.wixpress.dst.greyhound.sidecar.api.v1.Record, 3));
};


/**
 * @param {!Array<!proto.com.wixpress.dst.greyhound.sidecar.api.v1.Record>} value
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.HandleMessagesRequest} returns this
*/
proto.com.wixpress.dst.greyhound.sidecar.api.v1.HandleMessagesRequest.prototype.setRecordsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.Record=} opt_value
 * @param {number=} opt_index
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.Record}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.HandleMessagesRequest.prototype.addRecords = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.com.wixpress.dst.greyhound.sidecar.api.v1.Record, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.HandleMessagesRequest} returns this
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.HandleMessagesRequest.prototype.clearRecordsList = function() {
  return this.setRecordsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.Record.prototype.toObject = function(opt_includeInstance) {
  return proto.com.wixpress.dst.greyhound.sidecar.api.v1.Record.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.Record} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.Record.toObject = function(includeInstance, msg) {
  var f, obj = {
    partition: jspb.Message.getFieldWithDefault(msg, 1, 0),
    offset: jspb.Message.getFieldWithDefault(msg, 2, 0),
    payload: (f = msg.getPayload()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    headersMap: (f = msg.getHeadersMap()) ? f.toObject(includeInstance, proto.google.protobuf.StringValue.toObject) : [],
    key: (f = msg.getKey()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.Record}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.Record.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.wixpress.dst.greyhound.sidecar.api.v1.Record;
  return proto.com.wixpress.dst.greyhound.sidecar.api.v1.Record.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.Record} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.Record}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.Record.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPartition(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setOffset(value);
      break;
    case 3:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setPayload(value);
      break;
    case 4:
      var value = msg.getHeadersMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.google.protobuf.StringValue.deserializeBinaryFromReader, "", new proto.google.protobuf.StringValue());
         });
      break;
    case 5:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setKey(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.Record.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.wixpress.dst.greyhound.sidecar.api.v1.Record.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.Record} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.Record.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPartition();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getOffset();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getPayload();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getHeadersMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(4, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.google.protobuf.StringValue.serializeBinaryToWriter);
  }
  f = message.getKey();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
};


/**
 * optional int32 partition = 1;
 * @return {number}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.Record.prototype.getPartition = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.Record} returns this
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.Record.prototype.setPartition = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int64 offset = 2;
 * @return {number}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.Record.prototype.getOffset = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.Record} returns this
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.Record.prototype.setOffset = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional google.protobuf.StringValue payload = 3;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.Record.prototype.getPayload = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 3));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.Record} returns this
*/
proto.com.wixpress.dst.greyhound.sidecar.api.v1.Record.prototype.setPayload = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.Record} returns this
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.Record.prototype.clearPayload = function() {
  return this.setPayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.Record.prototype.hasPayload = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * map<string, google.protobuf.StringValue> headers = 4;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.google.protobuf.StringValue>}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.Record.prototype.getHeadersMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.google.protobuf.StringValue>} */ (
      jspb.Message.getMapField(this, 4, opt_noLazyCreate,
      proto.google.protobuf.StringValue));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.Record} returns this
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.Record.prototype.clearHeadersMap = function() {
  this.getHeadersMap().clear();
  return this;};


/**
 * optional google.protobuf.StringValue key = 5;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.Record.prototype.getKey = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 5));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.Record} returns this
*/
proto.com.wixpress.dst.greyhound.sidecar.api.v1.Record.prototype.setKey = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.Record} returns this
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.Record.prototype.clearKey = function() {
  return this.setKey(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.Record.prototype.hasKey = function() {
  return jspb.Message.getField(this, 5) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.HandleMessagesResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.com.wixpress.dst.greyhound.sidecar.api.v1.HandleMessagesResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.HandleMessagesResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.HandleMessagesResponse.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.HandleMessagesResponse}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.HandleMessagesResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.wixpress.dst.greyhound.sidecar.api.v1.HandleMessagesResponse;
  return proto.com.wixpress.dst.greyhound.sidecar.api.v1.HandleMessagesResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.HandleMessagesResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.HandleMessagesResponse}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.HandleMessagesResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.HandleMessagesResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.wixpress.dst.greyhound.sidecar.api.v1.HandleMessagesResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.wixpress.dst.greyhound.sidecar.api.v1.HandleMessagesResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.wixpress.dst.greyhound.sidecar.api.v1.HandleMessagesResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};


goog.object.extend(exports, proto.com.wixpress.dst.greyhound.sidecar.api.v1);
